version: '3.7'
services:
  db-server:
    container_name: db-server
    image: mysql:5.7.29
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'